[control]
node-control ansible_connection=community.general.incus

[api]
app-api ansible_connection=community.general.incus

[core]
app-core ansible_connection=community.general.incus

[db]
db-postgres ansible_connection=community.general.incus

[monitoring]
monitoring ansible_connection=community.general.incus

[storage]
ceph-node ansible_connection=community.general.incus
