---
- name: Configurar DNS permanente en todos los nodos
  hosts: all
  become: yes
  tasks:
    - name: Configurar DNS permanente
      copy:
        content: "nameserver 8.8.8.8\n"
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'

    - name: Evitar que systemd-resolved sobreescriba el DNS
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "^#?DNS="
        line: "DNS=8.8.8.8"
        create: yes

    - name: Reiniciar systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
      ignore_errors: yes
